version: '2.2'
services:
  es-master:
    image: es-master:7.4.2
    build:
      context: ./
      dockerfile: Dockerfile.es-master
    container_name: es-master
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-master:/usr/share/elasticsearch/data
      - ./elasticsearch-master.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /var/es-compose/elasticsearch_docker-compose_test/cre:/usr/share/elasticsearch/config/cre
    command: ["bin/elasticsearch-keystore", "add-file", "gcs.client.nsysu.credentials_file", "/usr/share/elasticsearch/config/cre/cre.json"]
    ports:
      - 9200:9200
    networks:
      - elastic

  es-data01:
    depends_on:
      - es-master
    image: es-data:7.4.2
    build:
      context: ./
      dockerfile: Dockerfile.es-data
    container_name: es-data01
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data01:/usr/share/elasticsearch/data
      - ./elasticsearch-data.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /var/es-compose/elasticsearch_docker-compose_test/cre:/usr/share/elasticsearch/config/cre
    command: ["bin/elasticsearch-keystore", "add-file", "gcs.client.nsysu.credentials_file", "/usr/share/elasticsearch/config/cre/cre.json"]
    networks:
      - elastic
  es-data02:
    image: es-data:7.4.2
    container_name: es-data02
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data02:/usr/share/elasticsearch/data
      - ./elasticsearch-data.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /var/es-compose/elasticsearch_docker-compose_test/cre:/usr/share/elasticsearch/config/cre
    command: ["bin/elasticsearch-keystore", "add-file", "gcs.client.nsysu.credentials_file", "/usr/share/elasticsearch/config/cre/cre.json"]
    networks:
      - elastic

  kibana:
    depends_on:
      - es-master
    image: docker.elastic.co/kibana/kibana:7.4.2
    # restart: on-failure
    container_name: kibana
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - elastic

volumes:
  es-master:
    driver: local
  es-data01:
    driver: local
  es-data02:
    driver: local

networks:
  elastic:
    driver: bridge